services:
  db:
    image: postgres:14
    container_name: stripe_db
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"  # Internal port stays 5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql

volumes:
  pgdata:
