version: "3.9"

services:
  db_dev:
    image: postgres:14
    container_name: stripe_db_dev
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  db_test:
    image: postgres:14
    container_name: stripe_db_test
    restart: always
    ports:
      - "5435:5432"
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata_dev:
  pgdata_test:
