"""robustesse Stripe: typages, nullable, colonnes extraites

Revision ID: 50f9e077da1c
Revises: eab4a799a8ad
Create Date: 2025-05-28 18:02:41.897974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f9e077da1c'
down_revision: Union[str, None] = 'eab4a799a8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
